[files]
extend-exclude = ["deps/*"]
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true
ignore-parent = true

[default]
binary = false
check-filename = true
check-file = true
unicode = true
locale = "en"

[default.extend-words]
Wholey = "Wholey"
comput = "comput"
strat = "strat"
numer = "numer"

[type.tex]
extend-glob = ["drudge/templates/report.tex"]

[type.tex.extend-words]
OT = "OT"

